name: Release Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: ./mcp

      - name: Create release assets
        run: |
          mkdir -p temp
          tar --exclude='./temp' -czvf temp/gas-fakes-ext.tar.gz .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            temp/gas-fakes-ext.tar.gz
